// =========================================================================
// LanguageService：中英切换词典（复刻自老项目 Module1.Tr，单机版 + 多机版合并）
//
// 干什么：Tr(中文) → 按 CurrentLanguage 返回中文/英文，全界面共用。
// 为什么合并：单机版 50+ 词条（固化/库位系）与多机版 60+ 词条（设备名/上报系）
//   有重叠也有各自独有；融合版必须两套都认识，否则切 Mode 后满屏中文回退。
//   已知瑕疵原样继承并标注：多机版把"橡胶装配PCB设备"译成和"外壳穿线"同一英文
//   （复制粘贴错误），此处修正，加注说明。
// 切换后 UI 刷新由各窗体 UpdateUI 负责（WPF 用 INotifyPropertyChanged + 资源重取）。
// =========================================================================

namespace PlcMesBridge.Core.Infrastructure;

public static class LanguageService
{
    /// <summary>全局语言：CH 中文 / EN 英文，记忆在 config.ini [setting] Language。</summary>
    public static string CurrentLanguage { get; set; } = "CH";

    private static readonly Dictionary<string, string> En = new()
    {
        // ---- 单机版（固化收料）----
        ["软件启动"] = "Software started",
        ["连接PLC成功"] = "Connect PLC Success",
        ["连接PLC失败"] = "Connect PLC Failed",
        ["连接PLC时发生异常"] = "Exception occurred while connecting to PLC",
        ["固化时间: "] = "Curing time: ",
        ["进入时间: "] = "Entry time: ",
        ["物料装载"] = "Material Loading",
        ["物料卸载"] = "Material Unloading",
        ["强制出料"] = "Forced Discharge",
        ["资料获取"] = "Data Acquisition",
        ["库位ID: "] = "Bin ID: ",
        ["库位ID="] = "Bin ID=",
        ["库位ID为空"] = "Bin ID is empty",
        ["产品ID="] = "Product ID=",
        ["未查询到相应数据"] = "No corresponding data found",
        ["产品号"] = "Product No.",
        ["产品ID"] = "Product ID",
        ["连接PLC"] = "Connect PLC",
        ["物料状态"] = "Material Status",
        ["PLC心跳"] = "PLC beat",
        ["PLC通信"] = "PLC Communication",
        ["是否退出?"] = "Are you sure you want to exit?",
        ["TEST"] = "TEST",
        ["库内总物料:"] = "Total Material:",
        ["静置已完成:"] = "Resting Completed:",
        ["正在静置:"] = "Currently Resting:",
        ["明日可完成:"] = "Will Complete Tomorrow:",
        // ---- MES 调试窗（两版共有）----
        ["MES 接口调试界面"] = "MES Interface Debugging",
        ["接口类型:"] = "API Type:",
        ["PLC地址:"] = "PLC Address:",
        ["读取长度:"] = "Read Length:",
        ["手动从PLC读取"] = "Manual Read PLC",
        ["手动上传到MES"] = "Manual Upload MES",
        ["请求 JSON:"] = "Request JSON:",
        ["MES 返回信息:"] = "MES Response:",
        ["请求内容不能为空"] = "Request content cannot be empty",
        ["请求中..."] = "Requesting...",
        ["读取失败:"] = "Read Failed:",
        ["发生错误:"] = "Error occurred:",
        ["MES 报警信息"] = "MES Alarm Message",
        ["关闭"] = "Close",
        ["MES 交互实时日志"] = "MES Real-time Logs",
        ["清空当前显示"] = "Clear Display",
        ["途程单号"] = "RC No.",
        ["制程代码"] = "Process Code",
        ["机台编号"] = "Machine No.",
        ["机台位置号"] = "Machine Loc No.",
        ["厂别"] = "Plant",
        ["参数/状态编码"] = "Param/Status Code",
        ["参数/状态值"] = "Param/Status Value",
        ["采集时间"] = "Collection Time",
        ["进出标志(I/O)"] = "In/Out Flag (I/O)",
        ["条码"] = "Barcode",
        ["员工工号(SP)"] = "Emp No.(SP)",
        ["员工工号(EMP)"] = "Emp No.(EMP)",
        ["工具号"] = "Tool No.",
        ["进出/上传时间"] = "In/Out Time",
        ["检测结果(0/1)"] = "Check Result (0/1)",
        ["板号(LINK)"] = "Board No.(LINK)",
        ["保存参数到本地"] = "Save Params Local",
        ["参数已成功保存到本地并生效全局!"] = "Params successfully saved and applied globally!",
        ["发送报文预览:"] = "Message Preview:",
        ["发生错误: URL 未在 MESConfig 中配置"] = "Error: URL not configured in MESConfig",
        // ---- 多机版（通用网关）----
        ["连接设备"] = "Connect",
        ["设备状态:"] = "Status:",
        ["设备状态: "] = "Status: ",
        ["扫描周期: "] = "Scan Cycle: ",
        ["产品ID:"] = "Product ID:",
        ["产品保压时间:"] = "Holding Time:",
        ["产品保压力值:"] = "Holding Pressure:",
        ["系统对时"] = "Time Sync",
        ["物料使用检查"] = "Material Check",
        ["物料绑定"] = "Material Bind",
        ["产品检查结果上报"] = "Inspection Report",
        ["设备进料上报"] = "Feed Report",
        ["设备出料上报"] = "Discharge Report",
        ["存图上报"] = "Image Report",
        ["产品工艺数据上报"] = "Process Data Report",
        ["打码内容请求"] = "Coding Request",
        ["已配置为不连接本工站PLC"] = "Configured not to connect PLC",
        ["MES许可"] = "MES Permission",
        ["产品1ID"] = "Product 1 ID",
        ["产品2ID"] = "Product 2 ID",
        ["MES绑定结果"] = "MES Bind Result",
        ["检查结果"] = "Inspection Result",
        ["图片ID"] = "Image ID",
        ["存图上报,没找到指定ID的图片文件,图片ID"] = "Image report, image not found by ID, ID",
        ["存图上报,没找到最新图片文件"] = "Image report, latest image not found",
        ["图片路径"] = "Image Path",
        ["参数当前值"] = "Current Value",
        ["参数标准值"] = "Standard Value",
        ["打码ID"] = "Coding ID",
        ["物料类别"] = "Material Type",
        ["图片文件不存在"] = "Image file not found",
        ["图片路径不存在,请查看详细日志"] = "Image path invalid, check logs",
        ["图片查看"] = "Image View",
        // 8 台设备名（注意：老项目把第 1 台错译成第 2 台英文，此处已修正）
        ["橡胶装配PCB设备"] = "Rubber Assembly PCB Equipment",
        ["外壳穿线半自动机构"] = "Shell threading semi-automatic mechanism",
        ["焊锡_2D检测_涂胶半自动机构"] = "Soldering_2D Inspection_Semi-Automatic Gluing Mechanism",
        ["外壳组件保压机构"] = "Shell Component Pressure-Holding Mechanism",
        ["外壳组件点胶_打标二维码设备"] = "Shell Component Dispensing and QR Code Marking Equipment",
        ["点胶固化收料机"] = "Glue Dispensing Curing and Material Collection Machine",
        ["测试线体-激光-基板焊接_打标_贴圆片体机"] = "Test Line - Laser - Substrate Welding_Marking_Pasting Disc Machine",
        ["测试线体-光效测试压力测试设备"] = "Test Line - Light Effect Test Pressure Testing Equipment",
        // 多机网关流程
        ["MES上传成功"] = "MES upload success",
        ["MES返回NG"] = "MES returned NG",
        ["MES解析失败"] = "MES parse failed",
        ["MES网络异常/超时"] = "MES network error/timeout",
        ["MES反序列化失败"] = "MES deserialize failed",
        ["MES返回数据解析为空"] = "MES response empty",
        ["MES返回数据解析异常"] = "MES response parse error",
        // API0033 不良明细字段（调试窗扩展，老项目无，新增）
        ["板号SN"] = "Board SN",
        ["顶底层"] = "Top/Bottom",
        ["线别"] = "Line No.",
        ["测试开始时间"] = "Test Start Time",
        ["测试结束时间"] = "Test End Time",
        ["检测状态"] = "Check Status",
        ["点位"] = "Dot Location",
        ["料仓位"] = "Bin Location",
        ["图片位置"] = "Image Location",
        ["错误码"] = "Error No.",
        ["实测值"] = "Actual Value",
        ["标准值"] = "Standard Value",
        ["上限"] = "Max Limit",
        // ---- 设置窗（登录门禁 + 运行模式切换，V0.0.2 新增）----
        ["设置"] = "Settings",
        ["登录"] = "Login",
        ["用户名"] = "Username",
        ["密码"] = "Password",
        ["确定"] = "OK",
        ["取消"] = "Cancel",
        ["保存"] = "Save",
        ["运行模式"] = "Run Mode",
        ["单机固化收料"] = "Single Machine",
        ["多机通用网关"] = "Multi-Machine Gateway",
        ["用户名或密码错误"] = "Wrong username or password",
        ["切换模式保存后自动重启软件"] = "Saving a mode change restarts the app automatically",
        ["设置已保存"] = "Settings saved",
        ["设置已保存，重启软件后生效"] = "Settings saved, restart to take effect",
        ["请登录后进入设置"] = "Please login to open settings",
        ["记住密码"] = "Remember me",
        // ---- PLC 配置窗（V0.0.4 新增，现场点鼠标配 PLC 用）----
        ["PLC配置"] = "PLC Config",
        ["单机PLC"] = "Single PLC",
        ["多机PLC"] = "Station PLCs",
        ["接口地址"] = "API Addresses",
        ["IP地址"] = "IP Address",
        ["端口"] = "Port",
        ["启用"] = "Enabled",
        ["协议"] = "Protocol",
        ["二进制"] = "Binary",
        ["命令字"] = "Command",
        ["完成位"] = "Done Bit",
        ["心跳地址"] = "Heartbeat Addr",
        ["固化时间地址"] = "Curing Addr",
        ["进入时间地址"] = "Entry Time Addr",
        ["PC时间地址"] = "PC Time Addr",
        ["库位地址"] = "Bin Addr",
        ["库位长度"] = "Bin Length",
        ["产品前缀"] = "Product Prefix",
        ["产品起始"] = "Product Start",
        ["产品步长"] = "Product Step",
        ["产品个数"] = "Product Count",
        ["产品读长"] = "Read Length",
        ["产品写长"] = "Write Length",
        ["报警地址"] = "Alarm Addr",
        ["测试连接"] = "Test",
        ["全部测试"] = "Test All",
        ["测试中..."] = "Testing...",
        ["测试用表单值直测保存后重启生效"] = "Tests use form values directly; saving restarts the app to apply",
        ["连接成功"] = "Connected",
        ["连接失败"] = "Connection failed",
        ["保存并重启"] = "Save & Restart",
        ["恢复缺省"] = "Defaults",
        ["模拟模式下配置仅对真机有效"] = "Simulation mode: settings apply to real PLC only",
        ["以下配置有误"] = "Invalid settings",
        ["触发地址"] = "Trigger Addr",
        ["数据地址"] = "Data Addr",
        ["MSG地址"] = "MSG Addr",
        ["DATA地址"] = "DATA Addr",
        ["状态地址"] = "Status Addr",
        ["完成地址"] = "Complete Addr",
        ["数据长度"] = "Data Length",
        ["已保存，重启软件后生效"] = "Saved, restart to take effect",
        ["IP地址无效"] = "Invalid IP address",
        ["端口范围1-65535"] = "Port must be 1-65535",
        ["PLC地址格式须为D/R+数字"] = "PLC address must be D/R + digits",
        ["不能为空"] = "Required",
        ["长度范围1-1000"] = "Length must be 1-1000",
        ["范围0-99999"] = "Must be 0-99999",
        ["范围1-10000"] = "Must be 1-10000",
        ["范围1-1000"] = "Must be 1-1000",
    };

    /// <summary>翻译。中文模式直接返回原文；英文模式查不到回退原文（老项目 Case Else 语义）。</summary>
    public static string Tr(string zh)
    {
        if (CurrentLanguage == "CH")
            return zh;
        return En.TryGetValue(zh, out string? en) ? en : zh;
    }
}
